// Originally generated from the static design's CATEGORY_DATA / CATEGORY_GROUPS
// blobs (the design file is deleted; this is now the canonical catalogue — edit it
// directly). Typed, with image paths pointing at the files in public/images.

export type StockState = 'in-stock' | 'out-of-stock'

export interface CatalogueItem {
  name: string
  price: number
  brand: string
  /** The design's own stock flag; live availability comes from productQty(). */
  stock: string
  /** Value on the category's facet axis (bag size, type, …). */
  facet: string
  image: string
}

export interface Category {
  /** Label of the facet these items vary on ("Bag size", "Type", …). */
  facetTitle: string
  items: CatalogueItem[]
}

export const CATEGORY_DATA: Record<string, Category> = {
  Beef: {
    facetTitle: 'Bag size',
    items: [
      {
        name: 'Beef Grower Pellet 25 kg',
        price: 24.95,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Beef Finisher Ration, bulk per tonne',
        price: 489,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Bulk',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Beef Mineral Loose Mix 20 kg',
        price: 38.5,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Beef Creep Feed Textured 25 kg',
        price: 27.75,
        brand: 'Semican',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Beef Protein Tub 90 kg',
        price: 132,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Bulk',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Beef Mineral Lick, 20 kg',
        price: 18.9,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Beef Supplement Tub, 45 kg',
        price: 59,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Cattle Ear Tags, pack of 25',
        price: 13.9,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  Dairy: {
    facetTitle: 'Bag size',
    items: [
      {
        name: 'Dairy Lactation Pellet 25 kg',
        price: 29.95,
        brand: 'Semican',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Dry Cow Ration 25 kg',
        price: 26.8,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Calf Milk Replacer 20 kg',
        price: 96,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Rumen Buffer Supplement 20 kg',
        price: 44,
        brand: 'Semican',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Heifer Developer Pellet 25 kg',
        price: 25.6,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Dairy Mineral Mix, 20 kg',
        price: 19.5,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Calf Milk Replacer, 20 kg',
        price: 54,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Colostrum Supplement, 500 g',
        price: 22.5,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
    ],
  },
  Swine: {
    facetTitle: 'Bag size',
    items: [
      {
        name: 'Sow Gestation Pellet 25 kg',
        price: 31.2,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Grower Finisher Ration, bulk per tonne',
        price: 465,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Bulk',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Piglet Starter Crumble 20 kg',
        price: 48.9,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Weaner Pellet 25 kg',
        price: 33.4,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Swine Mineral Mix, 20 kg',
        price: 17.8,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Piglet Starter Crumble, 20 kg',
        price: 28.5,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Swine Ear Tags, pack of 25',
        price: 13.9,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  Horses: {
    facetTitle: 'Bag size',
    items: [
      {
        name: 'Horse Sweet Feed 20 kg',
        price: 22.95,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Senior Horse Ration 25 kg',
        price: 34.5,
        brand: 'Semican',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Equine Mineral Supplement 20 kg',
        price: 41,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/cat-pet.png',
      },
      {
        name: 'Timothy Hay Cubes, bulk per tonne',
        price: 410,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Bulk',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Horse Mineral Block, 20 kg',
        price: 15.9,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Electrolyte Supplement, 5 kg',
        price: 32,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Curry Comb Set',
        price: 9.9,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
    ],
  },
  Sheep: {
    facetTitle: 'Bag size',
    items: [
      {
        name: 'Sheep Grower Pellet 25 kg',
        price: 26.4,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Ewe Gestation Ration, bulk per tonne',
        price: 438,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Bulk',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Lamb Creep Feed 20 kg',
        price: 29.8,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Sheep Mineral Block 20 kg',
        price: 13.9,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Sheep Drench, 5 L',
        price: 44,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Lambing Kit',
        price: 68,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-pet.png',
      },
      {
        name: 'Sheep Ear Tags, pack of 25',
        price: 13.9,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  Goats: {
    facetTitle: 'Bag size',
    items: [
      {
        name: 'Goat Grower Pellet 20 kg',
        price: 25.1,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Dairy Goat Ration 25 kg',
        price: 30.75,
        brand: 'Semican',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Goat Mineral Mix 20 kg',
        price: 16.2,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Goat Browse Supplement, 20 kg',
        price: 24,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Kid Milk Replacer, 10 kg',
        price: 36.5,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Goat Ear Tags, pack of 25',
        price: 13.9,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  Poultry: {
    facetTitle: 'Bag size',
    items: [
      {
        name: 'Layer Ration Pellet 25 kg',
        price: 23.4,
        brand: 'Semican',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Chick Starter Crumble 20 kg',
        price: 21.9,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Broiler Grower Feed 25 kg',
        price: 24.6,
        brand: 'Semican',
        stock: 'in-stock',
        facet: '25 kg',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Poultry Grit 20 kg',
        price: 11.5,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: '20 kg',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Layer Mash, 25 kg',
        price: 22,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/feed-bag.png',
      },
      {
        name: 'Poultry Oyster Shell, 20 kg',
        price: 10.9,
        brand: 'Shur-Gain',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Poultry Vitamin Supplement, 1 kg',
        price: 16.5,
        brand: 'Semican',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/feed-bag.png',
      },
    ],
  },
  'Poultry Supplies': {
    facetTitle: 'Type',
    items: [
      {
        name: 'Poultry Feeder, 20 L hanging',
        price: 34.95,
        brand: "Martin's Feeders & Equipment",
        stock: 'in-stock',
        facet: 'Feeders',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Poultry Waterer, 8 L',
        price: 24.5,
        brand: "Martin's Feeders & Equipment",
        stock: 'in-stock',
        facet: 'Waterers',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Chicken Coop Nesting Box, 4-hole',
        price: 149,
        brand: "Martin's Feeders & Equipment",
        stock: 'in-stock',
        facet: 'Housing',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Poultry Netting, 50 m',
        price: 89,
        brand: 'Gallagher',
        stock: 'in-stock',
        facet: 'Housing',
        image: '/images/cat-fencing-2.png',
      },
      {
        name: 'Poultry Leg Bands, pack of 50',
        price: 6.5,
        brand: "Martin's Feeders & Equipment",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Nest Box, single',
        price: 28,
        brand: "Martin's Feeders & Equipment",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Poultry Feeder, hanging',
        price: 24,
        brand: "Martin's Feeders & Equipment",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-chicks.png',
      },
    ],
  },
  'Barn Supplies': {
    facetTitle: 'Type',
    items: [
      {
        name: 'Barn Door Track Kit, 8 ft',
        price: 159,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Hardware',
        image: '/images/cat-barn-frame-3.png',
      },
      {
        name: 'Rubber Stall Mat, 4 x 6 ft',
        price: 68,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Flooring',
        image: '/images/cat-barn.png',
      },
      {
        name: 'LED Barn Light, 100 W',
        price: 44.9,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Lighting',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Barn Broom, heavy duty',
        price: 34.95,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Hardware',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Gate Latch, galvanized',
        price: 12.5,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Feed Scoop, 3 qt',
        price: 9.95,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Barn Fan, 20 in',
        price: 89,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-barn.png',
      },
      {
        name: 'Water Bucket, 5 gal',
        price: 14.95,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-barn-frame-3.png',
      },
      {
        name: 'Barn Extension Cord, 50 ft',
        price: 22,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  'Horse Supplies': {
    facetTitle: 'Type',
    items: [
      {
        name: 'Leather Halter, adjustable',
        price: 42,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Tack',
        image: '/images/cat-pet.png',
      },
      {
        name: 'Curry Comb Set',
        price: 18.5,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Grooming',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Stall Guard Chain',
        price: 26,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Stable',
        image: '/images/cat-barn.png',
      },
      {
        name: 'Fly Sheet, medium',
        price: 64,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Tack',
        image: '/images/cat-pet.png',
      },
      {
        name: 'Hoof Pick',
        price: 5.5,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Saddle Pad',
        price: 48,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-pet.png',
      },
      {
        name: 'Lead Rope, 10 ft',
        price: 12.5,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
    ],
  },
  'Vet Supplies': {
    facetTitle: 'Type',
    items: [
      {
        name: 'Vet Wrap Bandage, 4 in',
        price: 6.75,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Wound Care',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Livestock Syringe, 20 cc',
        price: 9.4,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Instruments',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Iodine Spray, 500 ml',
        price: 14.2,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Wound Care',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Ear Tag Applicator',
        price: 22.9,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Instruments',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Ear Tags, pack of 25',
        price: 14.5,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Thermometer, digital',
        price: 9.9,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Disposable Gloves, box of 100',
        price: 11,
        brand: 'Kane Veterinary Supplies',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  'Feeders & Troughs': {
    facetTitle: 'Type',
    items: [
      {
        name: 'Poly Feeder Trough, 8 ft',
        price: 214,
        brand: "Martin's Feeders & Equipment",
        stock: 'in-stock',
        facet: 'Poly',
        image: '/images/cat-livestock-feed-2.png',
      },
      {
        name: 'Steel Bunk Feeder, 10 ft',
        price: 389,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Steel',
        image: '/images/cat-barn.png',
      },
      {
        name: 'Round Bale Feeder',
        price: 298,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Steel',
        image: '/images/cat-trailer-2.png',
      },
      {
        name: 'Creep Feeder Panel',
        price: 175,
        brand: "Martin's Feeders & Equipment",
        stock: 'in-stock',
        facet: 'Poly',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Mineral Feeder, 200 lb',
        price: 210,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-barn.png',
      },
      {
        name: 'Hay Rack, wall mount',
        price: 95,
        brand: "Martin's Feeders & Equipment",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Grain Scoop, 2 qt',
        price: 7.5,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
    ],
  },
  'Bale Wrap': {
    facetTitle: 'Width',
    items: [
      {
        name: 'Bale Wrap, 750 mm x 1500 m',
        price: 118,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: '750 mm',
        image: '/images/cat-trailer-2.png',
      },
      {
        name: 'Bale Wrap, 500 mm x 1800 m',
        price: 96,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: '500 mm',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Net Wrap, 64 in x 9000 ft',
        price: 134,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: '750 mm',
        image: '/images/cat-trailer.png',
      },
      {
        name: 'Bale Wrap, 630 mm x 1500 m',
        price: 105,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-trailer-2.png',
      },
      {
        name: 'Silage Tape, roll',
        price: 19,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Bale Spike, single',
        price: 48,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  'Baler Twine': {
    facetTitle: 'Type',
    items: [
      {
        name: 'Baler Twine, 9600 ft two-roll',
        price: 74.5,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Poly',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Sisal Twine, 9000 ft',
        price: 68,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Sisal',
        image: '/images/cat-trailer.png',
      },
      {
        name: 'Bale Net Twine, 7200 ft',
        price: 72,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Twine Cutter Tool',
        price: 8.9,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Bale Twine Bag Holder',
        price: 15,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  'Heated Waterbowls': {
    facetTitle: 'Type',
    items: [
      {
        name: 'Heated Waterbowl, single',
        price: 289,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Single',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Heated Waterbowl, double',
        price: 389,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Double',
        image: '/images/cat-barn-frame.png',
      },
      {
        name: 'Tank De-Icer, 1500 W',
        price: 79,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Single',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Waterbowl Replacement Valve',
        price: 24,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Insulated Waterbowl Cover',
        price: 34,
        brand: "Stockman's Choice",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-barn-frame.png',
      },
      {
        name: 'Heat Tape, 25 ft',
        price: 38,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  'Chick Orders': {
    facetTitle: 'Breed',
    items: [
      {
        name: 'Layer Chicks, straight run',
        price: 5.25,
        brand: "Frey's Hatchery",
        stock: 'in-stock',
        facet: 'Layer',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Broiler Chicks, day-old',
        price: 4.1,
        brand: 'Feathered Acres',
        stock: 'in-stock',
        facet: 'Broiler',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Heritage Breed Chicks',
        price: 6.5,
        brand: "Frey's Hatchery",
        stock: 'in-stock',
        facet: 'Heritage',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Chick Waterer Base',
        price: 7.5,
        brand: 'Feathered Acres',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Brooder Heat Lamp',
        price: 26,
        brand: "Frey's Hatchery",
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-chicks.png',
      },
      {
        name: 'Chick Feeder, 1 qt',
        price: 6.5,
        brand: 'Feathered Acres',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-chicks.png',
      },
    ],
  },
  Seed: {
    facetTitle: 'Type',
    items: [
      {
        name: 'Pasture Seed Mix, 25 kg',
        price: 92,
        brand: 'OSC Seeds',
        stock: 'in-stock',
        facet: 'Forage',
        image: '/images/cat-garden-2.png',
      },
      {
        name: 'Cover Crop Blend, 25 kg',
        price: 78,
        brand: 'OSC Seeds',
        stock: 'in-stock',
        facet: 'Cover Crop',
        image: '/images/cat-garden.png',
      },
      {
        name: 'Spring Wheat Seed, bulk per tonne',
        price: 520,
        brand: 'OSC Seeds',
        stock: 'in-stock',
        facet: 'Cereal',
        image: '/images/cat-garden-2.png',
      },
      {
        name: 'Clover Seed, 10 kg',
        price: 54,
        brand: 'OSC Seeds',
        stock: 'in-stock',
        facet: 'Forage',
        image: '/images/cat-garden.png',
      },
      {
        name: 'Alfalfa Seed, 25 kg',
        price: 132,
        brand: 'OSC Seeds',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-garden-2.png',
      },
      {
        name: 'Corn Seed, per bag',
        price: 148,
        brand: 'OSC Seeds',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-garden.png',
      },
      {
        name: 'Soybean Seed, per bag',
        price: 142,
        brand: 'OSC Seeds',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-garden-2.png',
      },
    ],
  },
  'Fencing & Gates': {
    facetTitle: 'Type',
    items: [
      {
        name: 'T-Post, 6 ft galvanized',
        price: 9.85,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Posts',
        image: '/images/tpost.png',
      },
      {
        name: 'High-Tensile Wire, 4000 ft',
        price: 168,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Wire',
        image: '/images/cat-fencing-2.png',
      },
      {
        name: 'Fence Energizer, 5 Joule',
        price: 329,
        brand: 'Gallagher',
        stock: 'in-stock',
        facet: 'Wire',
        image: '/images/cat-fencing.png',
      },
      {
        name: 'Galvanized Farm Gate, 12 ft',
        price: 215,
        brand: 'Gallagher',
        stock: 'in-stock',
        facet: 'Gates',
        image: '/images/cat-fencing-2.png',
      },
      {
        name: 'Fence Insulator, pack of 25',
        price: 9.5,
        brand: 'Gallagher',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-fencing-2.png',
      },
      {
        name: 'Gate Hinge Set',
        price: 14,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Fence Wire Strainer',
        price: 18.5,
        brand: 'Gallagher',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-fencing-2.png',
      },
    ],
  },
  'New Equipment': {
    facetTitle: 'Equipment type',
    items: [
      {
        name: 'Compact Utility Tractor, 45 HP',
        price: 28900,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Tractors',
        image: '/images/rental-tractor.png',
      },
      {
        name: 'Rotary Mower, 6 ft',
        price: 3200,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Mowers',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Utility Trailer, 14 ft',
        price: 5600,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Trailers',
        image: '/images/cat-trailer-2.png',
      },
      {
        name: 'Post Pounder Attachment',
        price: 4100,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Attachments',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Compact Track Loader',
        price: 52000,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/rental-tractor.png',
      },
      {
        name: 'Zero-Turn Mower',
        price: 7800,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Rotary Cutter, 6 ft',
        price: 3600,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-trailer.png',
      },
    ],
  },
  'Used Equipment': {
    facetTitle: 'Equipment type',
    items: [
      {
        name: 'Used Compact Tractor, 800 hrs',
        price: 18500,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Tractors',
        image: '/images/service-tractor.png',
      },
      {
        name: 'Used Round Baler',
        price: 9800,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Balers',
        image: '/images/cat-trailer.png',
      },
      {
        name: 'Used Utility Trailer, 12 ft',
        price: 3100,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Trailers',
        image: '/images/cat-trailer.png',
      },
      {
        name: 'Used Skid Steer, 1200 hrs',
        price: 24500,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/rental-tractor.png',
      },
      {
        name: 'Used Manure Spreader',
        price: 6800,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-trailer-2.png',
      },
      {
        name: 'Used Zero-Turn Mower',
        price: 3900,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools-2.png',
      },
    ],
  },
  'Loader Attachments': {
    facetTitle: 'Attachment type',
    items: [
      {
        name: 'Loader Bucket, 72 in',
        price: 1450,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Buckets',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Pallet Fork Attachment',
        price: 980,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Forks',
        image: '/images/cat-trailer-2.png',
      },
      {
        name: 'Bale Grapple Attachment',
        price: 1980,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Grapples',
        image: '/images/cat-tools-2.png',
      },
      {
        name: 'Snow Blade, 84 in',
        price: 1290,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Blades',
        image: '/images/cat-trailer.png',
      },
      {
        name: 'Auger Attachment, 12 in',
        price: 1650,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
      {
        name: 'Trencher Attachment',
        price: 3200,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-trailer-2.png',
      },
      {
        name: 'Pallet Fork Attachment',
        price: 1450,
        brand: 'Marweld',
        stock: 'in-stock',
        facet: 'Item',
        image: '/images/cat-tools.png',
      },
    ],
  },
}

/** Top-level shop sections → the leaf categories they contain. */
export const CATEGORY_GROUPS: Record<string, string[]> = {
  Feed: ['Beef', 'Dairy', 'Swine', 'Horses', 'Sheep', 'Goats', 'Poultry'],
  'Farm Supply': [
    'Poultry Supplies',
    'Barn Supplies',
    'Horse Supplies',
    'Vet Supplies',
    'Feeders & Troughs',
    'Bale Wrap',
    'Baler Twine',
    'Heated Waterbowls',
  ],
  'Field & Yard': ['Chick Orders', 'Seed', 'Fencing & Gates'],
  Equipment: ['New Equipment', 'Used Equipment', 'Loader Attachments'],
}
